### PR TITLE
Add `file_prefix` to batch

### PR DESCRIPTION
**Pull request by Colelyman**
This adds the `file_prefix` parameter to the batch test to ensure that it continues working.

### CODE REVIEW

**Review by Snicker7 — APPROVED** [review]
Looks good and tests pass (with the correct branch)

**Comment by Snicker7** [comment]
image

**Comment by Snicker7** [comment]
@Colelyman I got an error here. It looks like it's due to a different version import for Pooled. Should we add it to the ignored lines?

**Comment by Colelyman** [comment]
@Snicker7 I think it is because of a different fastp version installed on your system. Can you try installing fastp 0.23.4 and see if the error persists?

I would be inclined not to ignore fastp versions at this point.

**Comment by Snicker7** [comment]
@Colelyman That did resolve it. LGTM.

**Pull request merged**
